### ISSUE TITLE
Installation Error. Please help!

### ISSUE THREAD

**Issue by Rainbeep** [chrmoritz/homebrew-starcheat#2]
Command "/usr/local/Cellar/starcheat/0.27.1/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-19GR_q/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-5YFuDS/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/starcheat/0.27.1/libexec/bin/../include/site/python2.7/Pillow" failed with error code 1 in /private/tmp/pip-req-build-19GR_q/

**Comment by chrmoritz** [comment]
I couldn't reproduce this. Could you please provide the full log from ` brew gist-logs chrmoritz/starcheat/starcheat --devel`?
